#import "OneginiConfigModel.h"

@implementation OneginiConfigModel

// Config model generated by SDK Configurator version: v5.3.0

+ (NSArray *)certificates
{
    return @[@"MIICnzCCAiWgAwIBAgIQf/MZd5csIkp2FV0TttaF4zAKBggqhkjOPQQDAzBHMQswCQYDVQQGEwJVUzEiMCAGA1UEChMZR29vZ2xlIFRydXN0IFNlcnZpY2VzIExMQzEUMBIGA1UEAxMLR1RTIFJvb3QgUjQwHhcNMjMxMjEzMDkwMDAwWhcNMjkwMjIwMTQwMDAwWjA7MQswCQYDVQQGEwJVUzEeMBwGA1UEChMVR29vZ2xlIFRydXN0IFNlcnZpY2VzMQwwCgYDVQQDEwNXRTEwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARvzTr+Z1dHTCEDhUDCR127WEcPQMFcF4XGGTfn1XzthkubgdnXGhOlCgP4mMTG6J7/EFmPLCaY9eYmJbsPAvpWo4H+MIH7MA4GA1UdDwEB/wQEAwIBhjAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwEgYDVR0TAQH/BAgwBgEB/wIBADAdBgNVHQ4EFgQUkHeSNWfE/6jMqeZ72YB5e8yT+TgwHwYDVR0jBBgwFoAUgEzW63T/STaj1dj8tT7FavCUHYwwNAYIKwYBBQUHAQEEKDAmMCQGCCsGAQUFBzAChhhodHRwOi8vaS5wa2kuZ29vZy9yNC5jcnQwKwYDVR0fBCQwIjAgoB6gHIYaaHR0cDovL2MucGtpLmdvb2cvci9yNC5jcmwwEwYDVR0gBAwwCjAIBgZngQwBAgEwCgYIKoZIzj0EAwMDaAAwZQIxAOcCq1HW90OVznX+0RGU1cxAQXomvtgM8zItPZCuFQ8jSBJSjz5keROv9aYsAm5VsQIwJonMaAFi54mrfhfoFNZEfuNMSQ6/bIBiNLiyoX46FohQvKeIoJ99cx7sUkFN7uJW"]; //Base64Certificates
}

+ (NSDictionary *)configuration
{
    return @{
             @"ONGServerType" : @"access",
             @"ONGServerVersion" : @"1.53.0",
             @"ONGAppIdentifier" : @"ExampleApp",
             @"ONGAppPlatform" : @"ios",
             @"ONGAppVersion" : @"6.2.6",
             @"ONGAppBaseURL" : @"https://mobile-security-proxy.onegini.com",
             @"ONGResourceBaseURL" : @"https://mobile-security-proxy.onegini.com/resources/",
             @"ONGRedirectURL" : @"oneginiexample://loginsuccess",
             };
}

+ (NSString *)serverPublicKey
{
    return @"DAAE54B0E19001C3A459AA617FA5B381E8ED7884AE3903F93B801A8179F3496C";
}

@end
